### PR TITLE
refactored profile image storing and retrieving method

### LINKED ISSUE #81: Refactoring profile image storing and retrieving method
### **Feature request**:
Currently the app uses firebase storage bucket to store profile image of user and to retrieve image to display on home page.
Since this method takes two much time to load
I would like to suggest an better way to handle this

### **Is your feature request related to a problem? Please describe
The app takes too much time to load user's profile pic and also it's not the correct way to do it

### **Describe the solution you'd like**:
1)we will store all the user information in the firebase cloud storage in the user document
2) the user document will have following fields
a) name
b) email
c) profileimage
3)In this way we won't requide http package to first convert imageurl to file and then upload it to storage bucket
4)Using this method we can store and retrieve data quickly

<hr/>

Plz assign me this issue i would like to work on it
@Sameerkash @ghackg11 @vaibhavarora102 @vilsi12

### PR DESCRIPTION
**Pull request by anotherwebguy**
# Description:

1)I have stored all the user information in the firebase cloud storage in the user document
2) the user document will have following fields
a) name
b) email
c) profileimage
3)In this way we won't requide http package to first convert imageurl to file and then upload it to storage bucket
4)Using this method we can store and retrieve data quickly

Fixes #81 

## Type of change:

- [x] Bug fix (non-breaking change which fixes an issue)

 
# Checklist:

- [x] My code follows the style guidelines of this project.
- [x] I have performed a self-review of my own code.
- [x] My changes generate no new warnings.

# Screenshots / Video:
Untitled

### CODE REVIEW

**Comment by anotherwebguy** [comment]
hope u will merge it soon @vaibhavarora102 @ghackg11 @Sameerkash

**Comment by ghackg11** [comment]
@anotherwebguy, can you please add comments to the code, otherwise, it's working fine.

**Comment by anotherwebguy** [comment]
> @anotherwebguy, can you please add comments to the code, otherwise, it's working fine.

Yeah sure i'll do it @ghackg11

**Comment by anotherwebguy** [comment]
> @anotherwebguy, can you please add comments to the code, otherwise, it's working fine.

done @ghackg11

**Comment by anotherwebguy** [comment]
Hope u will merge it soon @vaibhavarora102 @ghackg11 @Sameerkash

**Pull request merged**
