### PR TITLE
Profile Picture Added With Considering lagging and exception handling

### LINKED ISSUE #24: Profile Picture in Home Page
Hello, I want to add profile picture on the home page of this app...

If I can forward with that, please assign me to here..... I am also a gssoc'21 participant.......Waiting for your response... @ghackg11

### PR DESCRIPTION
**Pull request by SamarpanCoder2002**
# Description:

Profile Picture Added With Considering lagging and exception handling at Home Page with upload picture can store in firebase storage named as user id.

Fixes #24 

## Type of change:
Profile Picture Added With Considering lagging and exception handling

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

 
# Checklist:
- [x] My code follows the style guidelines of this project.
- [x] I have performed a self-review of my own code.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [ ] I have made corresponding changes to the documentation.
- [ ] My changes generate no new warnings.
- [x] I have added tests that prove my fix is effective or that my feature works.
- [x] New and existing unit tests pass locally with my changes.
- [x] Any dependent changes have been merged and published in downstream modules.

# Screenshots / Video:
<p>

</p>

Hope you review it and merge it soon @ghackg11 ...... Thanks

### CODE REVIEW

**Comment by SamarpanCoder2002** [comment]
Please review this pull request.... and merge it @ghackg11

**Comment by ghackg11** [comment]
@SamarpanCoder2002 I can not review it as I can not sign in to my app to check whether it's working fine or not. Sorry for the delay, but I can review this only after that would be fixed.

**Comment by SamarpanCoder2002** [comment]
> @SamarpanCoder2002 I can not review it as I can not sign in to my app to check whether it's working fine or not. Sorry for the delay, but I can review this only after that would be fixed.

Yah.... I solve the problem

**Comment by ghackg11** [comment]
it didn't worked @SamarpanCoder2002 , same error is there

**Comment by SamarpanCoder2002** [comment]
> it didn't worked @SamarpanCoder2002 , same error is there

@ghackg11 ..... I try to solve Sign-up problem in #35 ..... Please check this....... My machine gives no error regarding to that..... I already described to solve take a look in that problem ...... in that pull request

**Comment by ghackg11** [comment]
@SamarpanCoder2002, a funny bug happened, haha, when I was entering email, there was whitespace at the end of the email, due to which email was considered to be wrong in regexp you used to filter correct emails. When I removed the whitespace, it worked fine. Use the trim function to resolve this. And one more thing, when the password is wrong, it says email invalid, change that to email or password invalid as both can be the cases. thank you for your cooperation:)

**Comment by SamarpanCoder2002** [comment]
> @SamarpanCoder2002, a funny bug happened, haha, when I was entering email, there was whitespace at the end of the email, due to which email was considered to be wrong in regexp you used to filter correct emails. When I removed the whitespace, it worked fine. Use the trim function to resolve this. And one more thing, when the password is wrong, it says email invalid, change that to email or password invalid as both can be the cases. thank you for your cooperation:)

Ok Ok.... I will change as email or password invalid ... Thanks @ghackg11

**Comment by ghackg11** [comment]
> > @SamarpanCoder2002, a funny bug happened, haha, when I was entering email, there was whitespace at the end of the email, due to which email was considered to be wrong in regexp you used to filter correct emails. When I removed the whitespace, it worked fine. Use the trim function to resolve this. And one more thing, when the password is wrong, it says email invalid, change that to email or password invalid as both can be the cases. thank you for your cooperation:)
> 
> Ok Ok.... I will change as email or password invalid ... Thanks @ghackg11 

Mention not! I'll be there for any other help if needed, you can contact me here or at my discord or LinkedIn.

**Comment by SamarpanCoder2002** [comment]
> > > @SamarpanCoder2002, a funny bug happened, haha, when I was entering email, there was whitespace at the end of the email, due to which email was considered to be wrong in regexp you used to filter correct emails. When I removed the whitespace, it worked fine. Use the trim function to resolve this. And one more thing, when the password is wrong, it says email invalid, change that to email or password invalid as both can be the cases. thank you for your cooperation:)
> > 
> > 
> > Ok Ok.... I will change as email or password invalid ... Thanks @ghackg11
> 
> Mention not! I'll be there for any other help if needed, you can contact me here or at my discord or LinkedIn.

Yah sure ... Thanks for your kind words....It's my pleasure to work with that project
I will make a pull request about to change `email or password invalid` soon

**Comment by SamarpanCoder2002** [comment]
> > > > @SamarpanCoder2002, a funny bug happened, haha, when I was entering email, there was whitespace at the end of the email, due to which email was considered to be wrong in regexp you used to filter correct emails. When I removed the whitespace, it worked fine. Use the trim function to resolve this. And one more thing, when the password is wrong, it says email invalid, change that to email or password invalid as both can be the cases. thank you for your cooperation:)
> > > 
> > > 
> > > Ok Ok.... I will change as email or password invalid ... Thanks @ghackg11
> > 
> > 
> > Mention not! I'll be there for any other help if needed, you can contact me here or at my discord or LinkedIn.
> 
> Yah sure ... Thanks for your kind words....It's my pleasure to work with that project
> I will make a pull request about to change `email or password invalid` soon

Hello @ghackg11 I think you forget to attach labels of `GSSOC'21` and `level` here..... I am a GSSOC'21 participant..... Issue related that pull request also have that labels.... So I request you, please attach that labels here with that pull request...thank you @ghackg11

**Comment by ghackg11** [comment]
> > > > > @SamarpanCoder2002, a funny bug happened, haha, when I was entering email, there was whitespace at the end of the email, due to which email was considered to be wrong in regexp you used to filter correct emails. When I removed the whitespace, it worked fine. Use the trim function to resolve this. And one more thing, when the password is wrong, it says email invalid, change that to email or password invalid as both can be the cases. thank you for your cooperation:)
> > > > 
> > > > 
> > > > Ok Ok.... I will change as email or password invalid ... Thanks @ghackg11
> > > 
> > > 
> > > Mention not! I'll be there for any other help if needed, you can contact me here or at my discord or LinkedIn.
> > 
> > Yah sure ... Thanks for your kind words....It's my pleasure to work with that project
> > I will make a pull request about to change `email or password invalid` soon
> 
> Hello @ghackg11 I think you forget to attach labels of `GSSOC'21` and `level` here..... I am a GSSOC'21 participant..... Issue related that pull request also have that labels.... So I request you, please attach that labels here with that pull request...thank you @ghackg11 

Yup, I just forgot to add labels to this, thanks for reminding me:)

**Comment by SamarpanCoder2002** [comment]
> > > > > > @SamarpanCoder2002, a funny bug happened, haha, when I was entering email, there was whitespace at the end of the email, due to which email was considered to be wrong in regexp you used to filter correct emails. When I removed the whitespace, it worked fine. Use the trim function to resolve this. And one more thing, when the password is wrong, it says email invalid, change that to email or password invalid as both can be the cases. thank you for your cooperation:)
> > > > > 
> > > > > 
> > > > > Ok Ok.... I will change as email or password invalid ... Thanks @ghackg11
> > > > 
> > > > 
> > > > Mention not! I'll be there for any other help if needed, you can contact me here or at my discord or LinkedIn.
> > > 
> > > 
> > > Yah sure ... Thanks for your kind words....It's my pleasure to work with that project
> > > I will make a pull request about to change `email or password invalid` soon
> > 
> > 
> > Hello @ghackg11 I think you forget to attach labels of `GSSOC'21` and `level` here..... I am a GSSOC'21 participant..... Issue related that pull request also have that labels.... So I request you, please attach that labels here with that pull request...thank you @ghackg11
> 
> Yup, I just forgot to add labels to this, thanks for reminding me:)

it's my pleasure

**Pull request merged**
