### PR TITLE
Email and Password Authentication Added With Registerted Email Verification

### PR DESCRIPTION
**Pull request by SamarpanCoder2002**
Hello @ghackg11 , I added Email and Password Authentication. Added With Registered Email Verification....(#19)

What I added:
1. Sign-up and Log-in Feature integrate with Firebase
2. Store the user data cloud firestore
3. User only can log-in in to the app, if the registered email is verified with the link, send it to the registered email.....
4. If the user closes the app without log out, then after reopening the app, the user direct goes to the homepage not the welcome page and the user name will show in the home page.....
5. In Sign-up and Log-in, Every Field validator added(Such Like Email validator, password min length criteria)....

Hope you will review this pull request and merge this..... I am also a gssoc'21 participant..... If any problem occurs, you can freely tell me.... Waiting for your response....... Thanks

### CODE REVIEW

**Comment by ghackg11** [comment]
@SamarpanCoder2002, I must say you have done a great job! Everything is working fine except for a small issue. On the home screen, where it should display 'welcome $username' it is showing 'welcome $pssword'. Just correct this and I will merge your PR. Thank you and All the best :)

**Comment by SamarpanCoder2002** [comment]
> @SamarpanCoder2002, I must say you have done a great job! Everything is working fine except for a small issue. On the home screen, where it should display 'welcome $username' it is showing 'welcome $pssword'. Just correct this and I will merge your PR. Thank you and All the best :)

Thanks for the review @ghackg11 and sorry for the mistake..... The bugs associated with signup...... Now please first  sign up in a new account and then log in....... User name will display on the Home Screen.....  



Thanks @ghackg11

**Comment by SamarpanCoder2002** [comment]
Thanks for the merge @ghackg11 .... This is a nice project to work with

**Comment by ghackg11** [comment]
@SamarpanCoder2002 thank you for your contribution, you have done a great job! I have merged your PR, Hoping for more contributions from your side. All the best

**Comment by SamarpanCoder2002** [comment]
> @SamarpanCoder2002 thank you for your contribution, you have done a great job! I have merged your PR, Hoping for more contributions from your side. All the best

Yah sure.... I already raise a new issue about profile picture in home page(#24 ).... Please check it out @ghackg11 ....Thank you

**Pull request merged**
