### PR TITLE
issue-41 fixed

### LINKED ISSUE #41: Designing the tree info page
### **Feature request**:
Make the design of the Tree Info page and the wireframe for inspiration is given below.

### **Additional context:**
WhatsApp Image 2021-03-21 at 12 29 34 PM (1)

<hr/>

**Note:**
* If you want to work on an issue, you should check if it has already been assigned to anyone.

### PR DESCRIPTION
**Pull request by anotherwebguy**
# Description:

Designed the tree info page

Fixes #41  

## Type of change:

- [x] New feature (non-breaking change which adds functionality)

 
# Checklist:

- [x] My code follows the style guidelines of this project.
- [x] I have performed a self-review of my own code.
- [x] My changes generate no new warnings.

# Screenshots / Video:
image

plz review @ghackg11 @vaibhavarora102

### CODE REVIEW

**Comment by ghackg11** [comment]
image


The UI has an overflow error, and the exception also, you can see in the image. Also, the map is not showing the location yet.. Please recheck it.

**Comment by anotherwebguy** [comment]
> image
> image
> 
> The UI has an overflow error, and the exception also, you can see in the image. Also, the map is not showing the location yet.. Please recheck it.

the map was working in my phone anyways i'll take a look

**Comment by anotherwebguy** [comment]
> > image
> > image
> > The UI has an overflow error, and the exception also, you can see in the image. Also, the map is not showing the location yet.. Please recheck it.
> 
> the map was working in my phone anyways i'll take a look

for the map it takes few seconds to display

**Comment by anotherwebguy** [comment]
https://user-images.githubusercontent.com/66346161/114033171-a4ab3000-989a-11eb-85f3-b7a185c2f36b.mp4

i've made the changes and also u can see the map is working fine @ghackg11

**Comment by ghackg11** [comment]
@anotherwebguy , okay, let me recheck!

**Comment by anotherwebguy** [comment]
> @anotherwebguy , okay, let me recheck!

yes and plz wait for few seconds or a minute bcoz i noticed when running it for the first time it takes time to load the map

**Comment by ghackg11** [comment]
> > @anotherwebguy , okay, let me recheck!
> 
> yes and plz wait for few seconds or a minute bcoz I noticed when running it for the first time it takes time to load the map

Congo! It worked. Can you please make one more edit, make the map size flexible, so that it covers the whole screen portion left at the bottom.

**Comment by anotherwebguy** [comment]
> > > @anotherwebguy , okay, let me recheck!
> > 
> > 
> > yes and plz wait for few seconds or a minute bcoz I noticed when running it for the first time it takes time to load the map
> 
> Congo! It worked. Can you please make one more edit, make the map size flexible, so that it covers the whole screen portion left at the bottom.
> 

okay i'll do it

**Comment by anotherwebguy** [comment]
hey @ghackg11 i've made the changes u asked for now it covers the whole screen portion left at the bottom.

image

**Comment by ghackg11** [comment]
@anotherwebguy Works well! great work. Merging your PR.

**Comment by anotherwebguy** [comment]
> @anotherwebguy Works well! great work. Merging your PR.

Thanks :)

**Pull request merged**
