### PR TITLE
[QA] Added issue & PR templates

### LINKED ISSUE #26: [Need] Issue and PR template
Currently, we haven't any issue and PR template for this repo

### PR DESCRIPTION
**Pull request by Aryamanz29**
Closes #26
- [x] Added Issue and PR templates  into ` .github`

### CODE REVIEW

**Comment by Aryamanz29** [comment]
Kindly add labels to this PR @ghackg11

**Comment by vaibhavarora102** [comment]
hi @Aryamanz29  
it looks nice  to us but can you pls a general format for reporting issue also

**Comment by Aryamanz29** [comment]
@vaibhavarora102  Should I another template` ISSUE_TEMPLATES/general_issue.md` for that purpose? What do you think?

> hi @Aryamanz29
> it looks nice to us but can you pls a general format for reporting issue also

@vaibhavarora102  Should I another template` ISSUE_TEMPLATES/general_issue.md` for that purpose? What do you think?

**Like this**

Screenshot from 2021-03-17 00-07-39

**Comment by vaibhavarora102** [comment]
Yeah! Exactly

**Comment by Aryamanz29** [comment]
Ok I'll do that :)

**Comment by Aryamanz29** [comment]
Could you review this PR again? @vaibhavarora102

**Review by vaibhavarora102 — APPROVED** [review]

**Pull request merged**
