### PR TITLE
Issue #53 solved, PR generated again

### PR DESCRIPTION
**Pull request by DOOMSTERR**
Please view PR#54 for more details.

### CODE REVIEW

**Comment by DOOMSTERR** [comment]
Please view the conflicts, according to me there are some minor changes due to which this is arising.

**Comment by ghackg11** [comment]
i have resolved the conflicts @DOOMSTERR , now you can commit the changes required

**Comment by DOOMSTERR** [comment]
Please merge it

**Comment by ghackg11** [comment]
@DOOMSTERR , All the best for future contributions.

**Pull request merged**
